event_manager/config/routes.rb
Rails.application.routes.draw do
  
  

  get 'signup' => 'users#new'

  get 'users/edit'

  get 'users/show'
  
  get "users/index"
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  root "users#index"

  resources :users
  resources :events

  

end

event_manager/app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :creator, :class_name => "User"
end

event_manager/app/models/user.rb
class User < ActiveRecord::Base
  has_many :created_events, :foreign_key => "creator_id", :class_name => "Event"
  #belongs_to_many :events
end

event_manager/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private
  
  def logged_in_user
    unless logged_in?
      redirect_to login_url
    end
  end
  
end

event_manager/app/controllers/events_controller.rb
class EventsController < ApplicationController
  #before_action :logged_in_user, only: [:create, :destroy]
  
  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to users_path
    end
    
  end
  
  def new
    @event = Event.new
  end
  
  def destroy
  end
  
  def show
  end

  private
  
    def event_params
      params.require(:event).permit(:description)
    end
end

event_manager/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(name: params[:session][:name])
    if user
      log_in user
      redirect_to user
      
    else
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
  


end

event_manager/app/controllers/users_controller.rb
class UsersController < ApplicationController
  

  
  def new
    @user = User.new
  end

  def edit
  end
  
  def index
    @users = User.all
  end
  

  def show
    @user = User.find(params[:id])
    @event = @user.created_events
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render "new"
    end
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :tagline)
    end
  
end

event_manager/app/helpers/application_helper.rb
module ApplicationHelper
end

event_manager/app/helpers/events_helper.rb
module EventsHelper
end

event_manager/app/helpers/sessions_helper.rb
module SessionsHelper
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

event_manager/app/helpers/users_helper.rb
module UsersHelper
end

event_manager/app/views/events/_event.html.erb
<li>
<span><%= event.description %> | Created by: <%= event.creator.find(:creator_id) %> </span>
</li>

event_manager/app/views/events/new.html.erb
<p>Create a new event!</p>

<%= form_for(@event) do |f| %>
  <%= f.text_area :description, placeholder: "describe your event" %>
  <%= f.submit "Create" %>
<% end %>

event_manager/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EventManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

event_manager/app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

event_manager/app/views/users/index.html.erb
<h1>All Users</h1>
<ul>
<% @users.each do |s| %>
  <li><%= link_to s.name, user_path(s) %></li>
<% end %>
</ul>

event_manager/app/views/users/new.html.erb
<h1>sign Up!</h1>
<%= form_for (@user) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    
    <%= f.label :tagline %>
    <%= f.text_field :tagline %>
    
    <%= f.submit "Create!" %>
<% end %>

event_manager/app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p><%= @user.tagline %></p>
<% if logged_in? %>
  <h3>Events:</h3>
  <ol><%= render @event %></ol>
  <p><%= link_to "Add new event", new_event_path %></p>
  <p><%= link_to "Log Out", logout_path, method: "delete" %></p>
  

<% else %>
  <p><%= link_to "Log In", login_path %></p> 
  <% end %>

<%= link_to "new user", new_user_path %> | <%= link_to "all users", users_path %>